[supabase]
url = "https://bphmtxkchelyksumomha.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwaG10eGtjaGVseWtzdW1vbWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjA3MDQ4NzYsImV4cCI6MjAzNjI4MDg3Nn0.jYkJdFIcw4EIGizbJRa3X_PyyYgPA6mHDza7duJLEBY"
[connections.postgresql]
dialect = "postgresql"
host = "db.bphmtxkchelyksumomha.supabase.co"
port = "5432"
database = "postgres"
username = "postgres"
password = "Correcthorse3421$"
