[connections.postgresql]
dialect = "postgresql"
username = "postgres.qshtpwzpnifujdbwteqe"
password = "Insightpilot3421$"
host = "aws-0-ap-southeast-1.pooler.supabase.com"
port = "6543"
database = "postgres"


OPENAI_API_KEY="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"
